### PR TITLE
iOS Fix app delegate method signature

### PR DESCRIPTION
**Pull request by ichan-mb**
This is to make silent Xcode warning

### CODE REVIEW

**Comment by mortend** [comment]
Checking if this builds on Fuselibs.

**Comment by mortend** [comment]
```
/Users/travis/build/mortend/fuselibs/Tests/ManualTests/ManualTestingApp/build/iOS/Debug/src/Uno-iOS/AppDelegate.mm:71:141: error: no type or protocol named 'UIUserActivityRestoring'
/Users/travis/build/mortend/fuselibs/Tests/ManualTests/ManualTestingApp/build/iOS/Debug/src/Uno-iOS/AppDelegate.mm:43:1: warning: Implementing deprecated method [-Wdeprecated-implementations]
/Users/travis/build/mortend/fuselibs/Tests/ManualTests/ManualTestingApp/build/iOS/Debug/src/Uno-iOS/AppDelegate.mm:71:199: warning: conflicting parameter types in implementation of 'application:continueUserActivity:restorationHandler:': 'void (^ _Nonnull __strong)(NSArray * _Nullable __strong)' vs 'void (^__strong _Nonnull)(NSArray<id> * _Nullable __strong)' [-Wmismatched-parameter-types]
** BUILD FAILED **
```

This code is still being built by Xcode 9.2.

Maybe there is a method signature that will satisfy both Xcode versions, or maybe a `#if..#else..#endif` block can get around the problem.

**Comment by ichan-mb** [comment]
Oh I see, I have searched but couldn’t find a proper/straight way to check Xcode version using #if block. Maybe I will try it by checking Swift version? 

But If there’s no way to do it, I guess for know I will close this PR

**Comment by mortend** [comment]
> Xcode 9.2. Xcode 9.2 includes Swift 4 and SDKs for iOS 11.2, watchOS 4.2, tvOS 11.2, and macOS High Sierra 10.13.

Checking for iOS version might work too. I know we use similar checks some places in Fuselibs.

```cpp
#if defined(__IPHONE_13_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_13_0
// new signature
#else
// old signature
#endif
```

**Comment by ichan-mb** [comment]
I've made changes, it compiles fine on XCode 11 and iOS 13 but I don't know how to test it on the older XCode

**Comment by mortend** [comment]
Checking Fuselibs again.

**Pull request merged**
